## ==================Assignment_05_Numpy====================

In [ ]:
import numpy as np

In [2]:
list_ = [ '1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

## Yes, there is a difference in the data type of the list_ and array_list variables. The list_ variable is a Python list, and the array_list variable is a NumPy array

In [4]:
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


## Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [5]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
print("Data type of each element in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData type of each element in array_list:")
for element in array_list:
    print(type(element))

Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int) Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

## Yes, there will be a difference in the data type of the elements in array_list due to the specified dtype parameter. In this case, the elements of array_list will have a data type of int because you explicitly specified dtype=int during the NumPy array creation.

In [6]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
print("Data type of each element in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData type of each element in array_list:")
for element in array_list:
    print(type(element))

Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


## Consider the below code to answer further questions:
## import numpy as np
## num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
## num_array = np.array(object = num_list)
## Q4. Write a code to find the following characteristics of variable, num_array:
## (i) shape
## (ii) size

In [3]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [4]:
## 4 i ans
num_array.shape

(2, 3)

In [6]:
# ii ans
num_array.size

6

## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [9]:
arr=np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [10]:
identity_matrix = np.eye(5)

# Print the result
print("Identity Matrix of shape (5, 5):")
print(identity_matrix)

Identity Matrix of shape (5, 5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
